"""Pure read-only bridge: image -> remembered gesture/whitelisted procedure references.

A verified school output can suggest a procedure for a new observed raster,
but no memory text is evaluated as code and no image is generated by querying.
No canonical Native Memory integration, promotion or autonomous ACT.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from PIL import Image

from .drawing_school_v0 import black_pixels, bbox_of, signature_for
from .experience_memory_v1 import (
    code_fingerprint, verify_memory_bundle, MAX_EPISODES,
)


def propose_stored_procedure(
    bundle: str | Path, new_image: str | Path, *,
    max_signature_distance: int = 16, max_alternatives: int = 4,
) -> dict:
    if not 0<=max_signature_distance<=64 or not 1<=max_alternatives<=10:
        raise ValueError("bounded retrieval parameters required")
    root=Path(bundle).resolve(strict=True)
    validation=verify_memory_bundle(root)  # fail-closed if any evidence altered
    file=Path(new_image).resolve(strict=True)
    if file.stat().st_size>3*1024*1024:
        raise ValueError("query image too large")
    with Image.open(file) as source:
        observed=black_pixels(source.convert("L"))
    if not observed:
        return {
            "status":"HOLD_EMPTY_OBSERVATION","procedure_candidate":None,
            "source_ref":str(file),"memory_write_allowed":False,
            "decision_authority":"KX108_ONLY",
        }
    feat=signature_for(observed,bbox_of(observed))
    pack=json.loads((root/"candidate_skill_memory.json").read_text(encoding="utf-8"))
    skills=pack.get("skills")
    if not isinstance(skills,list) or not 1<=len(skills)<=MAX_EPISODES:
        raise ValueError("invalid candidate skill memory")
    ranked=sorted(
        ((sum(a!=b for a,b in zip(feat,skill["signature"])),skill)
         for skill in skills),
        key=lambda item:item[0],
    )
    nearest=ranked[:max_alternatives]
    options=[
        {"lesson_ref":s["lesson_ref"],
         "source_sha256":s["source_sha256"],
         "signature_mismatch_cells":dist,
         "last_training_error_pixels":s["last_error_pixels"],
         "gesture_count":len(s["gestures"]),
         "status":"CANDIDATE_NOT_CANONICALLY_VALIDATED"}
        for dist,s in nearest
    ]
    accepted=nearest[0][0]<=max_signature_distance
    status="PROCEDURE_CANDIDATE_RECALL_ONLY" if accepted else "HOLD_UNFAMILIAR_IMAGE"
    return {
        "schema":"BRODY_PROCEDURE_REACTIVATION_V1",
        "status":status,
        "query_source_ref":str(file),
        "interpretation":"8x8_NORMALIZED_INK_SIGNATURE_NOT_SEMANTIC",
        "context":"VISIBLE_REFERENCE_ONLY",
        "memory_replay_verified":validation["all_generated_artifacts_replayed"],
        "procedure_candidate":{
            "source_skill_ref":nearest[0][1]["lesson_ref"],
            "pipeline":["image-thinning","pixel-feedback-revision","drawing-motor-render"],
            "code_ref":[code_fingerprint(x) for x in (
                "image-thinning","pixel-feedback-revision","drawing-motor-render"
            )],
            "selection_rule":"MIN_INK_SIGNATURE_HAMMING_DISTANCE",
            "executing_from_memory_allowed":False,
            "human_review_required_for_canonical_promotion":True,
        } if accepted else None,
        "candidate_alternatives":options,
        "candidate_confidence_calibrated":False,
        "image_created":False,
        "native_memory_write_allowed":False,
        "decision_authority":"KX108_ONLY",
    }


def main(argv:list[str]|None=None)->int:
    p=argparse.ArgumentParser(description="Read-only skill/procedure recall from audited drawing experience")
    p.add_argument("--memory",type=Path,required=True)
    p.add_argument("--image",type=Path,required=True)
    p.add_argument("--max-distance",type=int,default=16)
    a=p.parse_args(argv)
    print(json.dumps(propose_stored_procedure(
        a.memory,a.image,max_signature_distance=a.max_distance
    ),ensure_ascii=False,indent=2))
    return 0


if __name__=="__main__":
    raise SystemExit(main())
